version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: AutoFixture.SeedExtensions
    versions:
    - 4.15.0
    - 4.16.0
  - dependency-name: AutoFixture.Xunit2
    versions:
    - 4.15.0
    - 4.16.0
  - dependency-name: AutoFixture.AutoMoq
    versions:
    - 4.15.0
    - 4.16.0
  - dependency-name: AutoFixture
    versions:
    - 4.15.0
    - 4.16.0
  - dependency-name: Microsoft.NETCore.Platforms
    versions:
    - 5.0.0
    - 5.0.1
  - dependency-name: Moq
    versions:
    - 4.16.0
